# absolute, relative, none
line_numbers_mode = relative 

spaces_for_tabs = true
caps_lock_as_escape = true
vim_mode = true
tab_size = 2
draw_lines = false
lines_color = #545454 
background_color = #141415 
text_color = #FFFFFF
cursor_color = #FFFFFF
under_cursor_color = #000000
line_numbers_color = #828282
